# Generated by Django 5.0.1 on 2024-03-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="username",
            field=models.TextField(null=True),
        ),
    ]
